name: Request for GitHub Actions Secrets Access
description: Give your project visibility to org-wide GitHub Actions Secrets
title: "[GitHub Actions Secrets Request]: <short description>"
labels: ["support"]
projects: ["block/1"]
body:
  - type: markdown
    attributes:
      value: |
        # Access Requested and Additional Information 

  - type: dropdown
    id: organization
    attributes:
      label: GitHub Organization
      description: In which GitHub Organization? OSPO supports those listed below.
      options:
        - block
      default: 0
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: Repository Name
      description: The repository that needs access
      placeholder: ex. "goose"
    validations:
      required: true

  - type: checkboxes
    id: secrets
    attributes:
      label: Checklist
      options:
        - label: Maven Central publishing credentials (for xyz.block namespace) - SONATYPE_USERNAME_BLOCK, SONATYPE_PASSWORD_BLOCK, GPG_SECRET_KEY, GPG_SECRET_PASSPHRASE
        - label: Maven Central publishing credentials (for app.cash, com.squareup namespaces) - SONATYPE_USERNAME_SQUARE, SONATYPE_PASSWORD_SQUARE, GPG_SECRET_KEY, GPG_SECRET_PASSPHRASE
        - label: NPM Registry publishing credentials - NPM_PUBLISH_TOKEN
        - label: Other (provide input below)


  - type: input
    id: other
    attributes:
      label: Other
      description: The name of the secret or description of access you need from the org level
      placeholder: SECRET_NAME
    validations:
      required: false
