name: Request for Support
description: OSPO General Purpose Support
title: "[Support Request]: <short description>"
labels: ["support"]
projects: ["block/1"]
body:
  - type: textarea
    id: request
    attributes:
      label: Request
      description: How can the Open Source Program Office help you?
      placeholder: Describe your issue.
    validations:
      required: true
